---
title: "Messages visualized"
output:
  html_document:
    theme: flatly
---

```{r setup, include=FALSE}
library(ggplot2)
library(data.table)
load("../messages_dt_final.RData")
knitr::opts_chunk$set(echo = FALSE,
                      warning = FALSE,
                      message = FALSE,
                      fig.width = 10,
                      fig.height = 7)
```

## total messages by week
```{r}
ggplot2::ggplot(dt[plus5000 == T, 
          .(.N, date = as.Date(min(time))), 
          by = .(year(time), 
                 week(time), 
                 threadname)],
       aes(x = date, y = N, color = threadname, fill = threadname)) +
  geom_bar(stat = "identity", position = "stack") +
  theme(legend.text = element_text(size = 6),
        legend.key.size = unit(2, "mm"),
        legend.spacing = unit(1, "mm"))
```

## messages by week & thread
```{r}
ggplot(dt[plus5000 == T, 
          .(.N, date = as.Date(min(time))), 
          by = .(year(time), 
                 week(time), 
                 threadname)],
       aes(x = date, y = N, color = threadname, fill = threadname)) +
  geom_bar(stat = "identity", position = "stack") +
  scale_color_discrete(guide = FALSE) + 
  scale_fill_discrete(guide = FALSE) + 
  facet_wrap(~threadname, scales = "free_y")
```

## messages distribution by time
```{r}
ggplot(dt[plus5000 == T],
       aes(x = hour(time), fill = threadname)) +
  geom_histogram(bins = 24) +
  facet_wrap(~threadname, scales = "free_y")
```

## last message before going to bed
```{r}
ggplot(dt[by_me == T,
          .(lastmessage = max(difftime(time, as.POSIXct(realday), units = "hours"))), 
          by = realday],
       aes(x = realday, y = lastmessage)) +
  geom_point(alpha = 0.5) +
  geom_hline(yintercept = 24) +
  scale_y_continuous(labels = function(x) paste0(x %% 24, ":00"))
```

## proportion of messages written by me
```{r}
ggplot(dt[plus1000 == T],
       aes(x = threadname, fill = by_me)) +
  geom_bar(position = "fill", stat = "count") +
  geom_hline(yintercept = 0.5, linetype = "dashed") +
  theme(axis.text = element_text(size = 7, angle = 65, hjust = 1))
```

## who usually writes the first message
```{r}
ggplot(dt[plus5000 == T,
          .(by_me = .SD[id == min(id), by_me]),
          by = .(threadname, realday)],
       aes(x = year(realday), fill = by_me)) +
  geom_bar(position = "fill", stat = "count") +
  geom_hline(yintercept = 0.5, linetype = "dashed") +
  theme(axis.text = element_text(size = 7, angle = 65, hjust = 1)) +
  facet_wrap(~threadname) +
  ggtitle("Who messages first?")
```

## ... and the last message?
```{r}
ggplot(dt[plus5000 == T,
          .(by_me = .SD[id == max(id), by_me]),
          by = .(threadname, realday)],
       aes(x = year(realday), fill = by_me)) +
  geom_bar(position = "fill", stat = "count") +
  geom_hline(yintercept = 0.5, linetype = "dashed") +
  theme(axis.text = element_text(size = 7, angle = 65, hjust = 1)) +
  facet_wrap(~threadname) + 
  ggtitle("Who messages last?")
```

## average response time
```{r}
ggplot(dt[plus5000 == T & !(is.na(response_delay)) & time > "2011-04-01",
          .(response_delay = mean(response_delay, trim = 0.05), date = as.Date(min(time))), 
          by = .(year(time), 
                 month(time),
                 by_me)],
       aes(x = date, y = abs(response_delay), color = by_me, fill = by_me)) +
  geom_point() +
  xlab("Date") + ylab("Average response delay (mins)")
```

## ...per thread
```{r}
ggplot(dt[plus5000 == T & !(is.na(response_delay)),
          .(response_delay = mean(response_delay, trim = 0.05), date = as.Date(min(time))), 
          by = .(year(time), 
                 month(time),
                 by_me,
                 threadname)],
       aes(x = date, y = abs(response_delay), color = by_me, fill = by_me)) +
  geom_point() +
  facet_wrap(~threadname) + 
  scale_y_log10() +
  xlab("Date") + ylab("Average response delay (mins)") 

```